[package]
name = "bfr"
version = "1.0.0"
edition = "2021"
description = "brainfuck made in rust"
authors = ["Gurkan <hello@gurkz.me>"]
license = "LGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
